[package]
name = "drillx"
version = "0.2.0"
description = "Drillx is a proof-of-work algorithm for Ore cryptocurrency mining."
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/hardhatchad/drillx"
readme = "../README.md"
keywords = ["solana", "crypto", "mining"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "drillx"

[features]
default = ["full"]
benchmark = []
compiler = ["equix/compiler"]
cuda = ["cc"]
full = ["equix/full"]
solana = ["solana-program"]

[dependencies]
blake3 = { workspace = true }
equix = { workspace = true }
solana-program = { workspace = true, optional = true }
strum = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, default-features = true, features = ["html_reports"] }

[build-dependencies]
cc = { version = "1.0", optional = true }


[[bench]]
name = "drillx_loop"
harness = false
